# ServiceAccount for monitoring.h to create/update Monitoring CRDs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eq-task-monitoring-sa
  namespace: default
---
# Role to allow creating and updating Monitoring CRDs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eq-task-monitoring-role
  namespace: default
rules:
- apiGroups: ["rt.francescol96.univr"]
  resources: ["monitorings"]
  verbs: ["get", "list", "create", "update", "patch"]
---
# RoleBinding to bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eq-task-monitoring-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: eq-task-monitoring-sa
  namespace: default
roleRef:
  kind: Role
  name: eq-task-monitoring-role
  apiGroup: rbac.authorization.k8s.io